### ISSUE TITLE
Issue setting an heic 

### ISSUE THREAD

**Issue by therealX01D** [bcyran/timewall#115]
Dear sir,
Hope you're doing well
I installed package from aur and when i run the set command it returns this 
```sh
Error: could not set wallpaper: No such file or directory (os error 2)
```
my os is Archlinux
any help is greatly appreciated
edit:
the image file exists

best regards

**Comment by therealX01D** [comment]
the info command result
```sh
Size: 80980812B
Resolution: 5120x2880px
Schedule type: time
Number of images: 19
Number of frames: 19
Schedule:
Frame Image Time
1     1     00:00:00
2     2     04:00:00
3     3     05:00:00
4     4     06:00:00
5     5     06:30:00
6     6     07:00:00
7     7     07:30:00
8     8     08:00:00
9     9     09:00:00
10    10    11:00:00
11    0     12:00:00
12    11    13:00:00
13    12    14:00:00
14    13    17:00:00
15    14    19:00:00
16    15    20:00:00
17    16    21:00:00
18    17    22:00:00
19    18    23:00:00
Appearance:
Light: 0
Dark: 16
```

**Comment by bcyran** [comment]
Hi!
What DE/WM are you using? I suspect it's not of the supported ones - see [`wallpaper-rs` lib docs](https://docs.rs/wallpape-rs/latest/wallpape_rs/). You can still use timewall but you will need to configure it to use your custom command to set the wallpaper. See [Custom wallpaper setting command](https://github.com/bcyran/timewall?tab=readme-ov-file#custom-wallpaper-setting-command).

The error message is impressively unhelpful, I should fix that.

**Comment by therealX01D** [comment]
Thank you for replying,
I'm using hyprland with hyprpaper desktop manager have you tried using it with the plugin before??

**Comment by bcyran** [comment]
I find `hyprpaper` extremely inconvenient to use because of the fact that wallpaper setting is a multi step process involving loading and unloading of images. I don't use it precisely for this reason. It's absolutely possible to create some kind of script to make it easier. In fact that's precisely what `hyprpaper` readme suggests:

> In any and all cases when you don't mind waiting 300ms for the wallpaper to change, consider making a script that:
>  * preloads the new wallpaper
>  * sets the new wallpaper
>  * unloads the old wallpaper (to free memory)
 
However, I would suggest using [`swww`](https://github.com/LGFae/swww) instead. You just have to ensure that `swww-daemon` is running and then the following config:
```toml
[setter]
command = ['swww', 'img', '%f']
```
added to `~/.config/timewall/config.toml` works great.

**Comment by bcyran** [comment]
I published a new release which should make the error message a bit more informative and which includes a command example in the generated config file :smiley:.

**Comment by therealX01D** [comment]
Ok thank you sir, used swww as suggested and all is working perfectly + the new error messages is a great addition
