### ISSUE TITLE
timewall set /path/to/image.heic after reboot need re-ran.

### ISSUE THREAD

**Issue by rizitis** [bcyran/timewall#116]
Hello, thanks for your nice work!

- [ OS] Slackware-current
- [DE] Gnome-46
- [init] SysVinit 
- [timewall] 1.2.0

I have build and install, {as [package](https://github.com/rizitis/One4All_SlackBuild/tree/main/timewall) }, timewall-1.2.0 for Slackware-current.
My `~/.config/timewall/config.toml` is:
```
[location]
lat = 35.51
lon = 24.01
```
I also use rc.timewall script to call `timewall set --daemon` on startup:
```
#!/bin/sh
#
# rc.timewall: Slackware-style init script for timewall (dynamic wallpaper daemon)
# you can call it from rc.local on start up.

DAEMON=/usr/bin/timewall  # Adjust the path if your timewall binary is elsewhere
DAEMON_OPTS="set --daemon"
PIDFILE=/var/run/timewall.pid
LOGFILE=/var/log/timewall.log

start() {
    echo "Starting timewall..."
    if [ -f "$PIDFILE" ]; then
        echo "timewall is already running."
        return 1
    fi
    nohup $DAEMON $DAEMON_OPTS > $LOGFILE 2>&1 &
    echo $! > "$PIDFILE"
    echo "timewall started with PID $(cat $PIDFILE)."
}

stop() {
    echo "Stopping timewall..."
    if [ ! -f "$PIDFILE" ]; then
        echo "timewall is not running."
        return 1
    fi
    kill "$(cat $PIDFILE)"
    rm -f "$PIDFILE"
    echo "timewall stopped."
}

restart() {
    stop
    sleep 2
    start
}

status() {
    if [ -f "$PIDFILE" ]; then
        echo "timewall is running with PID $(cat $PIDFILE)."
    else
        echo "timewall is not running."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
``` 

My issue is this:<br>
After reboot although daemon is up and wallpaper is the last one I used. Wallpaper status stuck in the status before last shutdown.<br>
For example if I shutdown laptop 12:00am and power on again 8:00 am, wallpaper will stuck in 12:00am status and not refresh although daemon is ranning.<br>
 And If I ran manually `timewall set /path/to/image.heic` then immediately switch to the correct status and following time cycle as excepted during day time!<br>
 I was wondering if you have any suggestions how I can handle this "personal" issue?<p>
 
 thank you.

**Comment by rizitis** [comment]
If I check log file I have this error when I call daemon: `cat timewall.log 
Error: no image to set given
`

**Comment by bcyran** [comment]
Hi! I see that you already solved the issue but I will share my thoughts anyway.

Am I correct in the assumption that your rc script was ran as root? timewall stores its data, including the currently set wallpaper, in the home directory of the user who runs it. So if your daemon runs as root, it won't be able to see settings made using your regular user account. Basically, you need to run all timewall commands as the same user.

You could work around that by overriding the cache directory using `TIMEWALL_CACHE_DIR` env variable. Just a warning that it's undocumented, exists mainly for tests and isn't really a feature.
