### ISSUE TITLE
Cargo build failing

### ISSUE THREAD

**Issue by snocodile** [bcyran/timewall#27]
Just wanted to install your app but trying it via cargo gave me the following error unfortunately: 

> note: /bin/ld: cannot find -lheif: No such file or directory
>           collect2: error: ld returned 1 exit status

Any pointers for this? I have libheif and libheif-devel installed though and will try the Tarball now.

**Comment by bcyran** [comment]
Huh, it's really hard to say for me. I'm definitely not an expert with rust and cargo ecosystem and frankly, this does sound like a problem with your environment.

I guess if I were you, I would try to verify whether and where `libheif` is installed:
```bash
ldconfig -p | grep libheif
```
And possibly try to manually provide the dir where the library resides to cargo:
```bash
RUSTFLAGS='-L my/lib/location' cargo [...]
```
