### ISSUE TITLE
Change default target to graphical-session

### ISSUE THREAD

**Issue by 0x011011110** [bcyran/timewall#28]
Just a suggestion; I noticed that with the `WantedBy=default.target`, that timewall would start, but it wouldn't actually set the wallpaper when logging in to Gnome, because it was started before the compositor is running.  Changing the target to be `WantedBy=graphical-session.target` makes it so that it doesn't actually start until you're in a graphical session.

This is just a suggestion, and I am by no means a systemd unit expert.

**Comment by bcyran** [comment]
Hey, I just tried it on my system and couldn't get it to work that way. Also, it's actually the first time I'm hearing about `graphical-session.target`. I think I will stick with `default.target` as it seems like a reasonable, well, default :wink:. I think most Linux users should be able to adjust it to their needs. Thank you for the suggestion though!

**Comment by 0x011011110** [comment]
That isn't a problem, there's definitely something going on though; with it set to default, it doesn't work properly with Gnome, logging in via GDM3.  Here, when that happens, timewall errors out and says that it couldn't connect to the compositor.
