### ISSUE TITLE
[Feature] Add a command to clear correctly the cache

### ISSUE THREAD

**Issue by kernelb00t** [bcyran/timewall#82]
Wallpapers can take rapidly big amounts of storage when trying different wallpapers.
We can clear the cache manually, but this removes all the wallpaper caches and the background will become black. A simple `timewall clear-cache` would be very useful, to only clear the cache of the wallpapers not set.

**Comment by bcyran** [comment]
Hi, this sounds useful indeed. I'll try to add it soon :smile:. Thanks!

**Comment by kernelb00t** [comment]
Perfect, I'm waiting for it!

**Comment by bcyran** [comment]
Implemented in [1.1.0](https://github.com/bcyran/timewall/releases/tag/1.1.0)

**Comment by kernelb00t** [comment]
Works flawlessly! Thanks! :+1:
